<?php

return [
    'SJ4WEB_FW_WHITELIST_IPS' => [
        '88.125.107.215',
        '31.35.195.23',
        '2a01:e0a:55a:f5e0::/64',
        '2001:861:43c0:3170::/64',
        '91.172.92.135'
    ],
    'SJ4WEB_FW_SAFEBOTS' => [
        'googlebot', 'bingbot', 'duckduckbot', 'msnbot',
        'slurp', 'facebot', 'ia_archiver', 'applebot', 'gptbot',
        'oai-searchbot', 'chatgpt-user', 'perplexitybot', 'ccbot'
    ],
    'SJ4WEB_FW_MALICIOUSBOTS' => ['ahrefsbot', 'semrushbot', 'mj12bot', 'dotbot', 'rogerbot', 'linkpadbot',
        'screaming frog seo spider', 'sitebulb', 'seokicks-robot', 'linkchecker','baiduspider',
        'netpeak spider', 'buzzbot', 'spbot', 'curl', 'python-requests', 'wget',
        'oppo\\sa33', '(?:c99|php|web)shell', 'site.{0,2}copier', 'base64_decode',
        'bin/bash', 'disconnect', 'eval', 'unserializ', 'libwww-perl', 'pycurl',
        'scan', 'ahref', 'acapbot', 'acoonbot', 'alexibot', 'asterias', 'attackbot',
        'babbar', 'barkrowler', 'backdorbot', 'becomebot', 'binlar', 'blackwidow',
        'blekkobot', 'blexbot', 'blowfish', 'bullseye', 'bunnys', 'butterfly',
        'bytespider', 'careerbot', 'casper', 'checkpriv', 'cheesebot', 'cherrypick',
        'chinaclaw', 'choppy', 'clshttp', 'cmsworld', 'copernic', 'copyrightcheck',
        'cosmos', 'crescent', 'cy_cho', 'datacha', 'demon', 'diavol', 'discobot',
        'dittospyder', 'dotbot', 'dotnetdotcom', 'dumbot', 'econtext',
        'emailcollector', 'emailsiphon', 'emailwolf', 'eolasbot', 'eventures',
        'extract', 'eyenetie', 'feedfinder', 'flaming', 'flashget', 'flicky',
        'foobot', 'fuck', 'g00g1e', 'getright', 'gigabot', 'go-ahead-got', 'gozilla',
        'grabnet', 'grafula', 'harvest', 'heritrix', 'httracks?', 'icarus6j', 'jetbot',
        'jetcar', 'jikespider', 'kmccrew', 'leechftp', 'libweb', 'liebaofast',
        'linkscan', 'linkwalker', 'loader', 'lwp-download', 'majestic', 'masscan',
        'miner', 'mechanize', 'mj12bot', 'morfeus', 'moveoverbot', 'netmechanic',
        'netspider', 'nicerspro', 'nikto', 'ninja', 'nominet', 'nutch', 'octopus',
        'pagegrabber', 'planetwork', 'postrank', 'proximic', 'purebot', 'queryn',
        'queryseeker', 'radian6', 'radiation', 'realdownload', 'remoteview',
        'rogerbot', 'scan', 'scooter', 'seekerspid', 'serpstatbot', 'semalt',
        'siclab', 'sindice', 'sistrix', 'sitebot', 'siteexplorer', 'sitesnagger',
        'skygrid', 'smartdownload', 'snoopy', 'sosospider', 'spankbot', 'spbot',
        'sqlmap', 'stackrambler', 'stripper', 'sucker', 'surftbot', 'sux0r',
        'suzukacz', 'suzuran', 'takeout', 'teleport', 'telesoft', 'true_robots',
        'turingos', 'turnit', 'vampire', 'vikspider', 'voideye', 'webleacher',
        'webreaper', 'webstripper', 'webvac', 'webviewer', 'webwhacker', 'winhttp',
        'wwwoffle', 'woxbot', 'xaldon', 'xxxyy', 'yamanalab', 'yioopbot', 'youda',
        'zeus', 'zmeu', 'zune', 'zyborg', '80legs', 'curl', 'wget', 'python-requests',
        'python-urllib', 'scrapy', 'httpclient', 'nikto', 'libwww-perl', 'nmap',
        'fimap', 'httprint', 'httprecon', 'zmeu', 'bcrawl', 'blackwidow', 'paros',
        'w3af', 'nessus', 'whatweb', 'openvas', 'sf', 'jaeles', 'arachni', 'acunetix',
        'netsparker', 'dirbuster', 'dirb', 'gobuster', 'webscarab', 'webshag',
        'metasploit', 'sqlninja', 'sqlsus', 'sqlbrute', 'sqlpwn', 'sqliv', 'sqlmap',
        'sqlmate', 'sqlscan', 'sqlsec', 'sqlsploit', 'sqltool', 'sqlworm', 'sqlx',
        'sqlz'],
    'SJ4WEB_FW_COUNTRIES_BLOCKED' => [],
    'SJ4WEB_FW_SCORE_LIMIT_BLOCK' => -40,
    'SJ4WEB_FW_SCORE_LIMIT_SLOW' => -10,
    'SJ4WEB_FW_BLOCK_DURATION' => 3600, // en secondes
    'SJ4WEB_FW_ENABLE_SLEEP' => true,
    'SJ4WEB_FW_SLEEP_DELAY_MS' => 1500,
    'SJ4WEB_FW_LOG_ENABLED' => true,
    'SJ4WEB_FW_ACTIVATE_FIREWALL' => false,

];
